spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAJPdxqawLRjjWQPv0EGzSZxm8DoPa9SGekaCJ8OTaADlmXLP4zQzM5/Rpa0uEIKlrY1UpYjJO3Fq5t9Ssu5J/Kwq88AWeNMhjWg4wh54wZgy8N+1lIWLGfmO7z75n+iLOB5aFUaVqwuVQaLLic1aTjtKzP2ltD0AC+PrEmlq7ORAyYNDW6lNqduvlpvEOyzHdqm84LO0dBfNcsnPygDZN09tqjnLnuuOVYuXoDNWjK6vXgf7d3gJ5XA8gnrMh7fcj9fG+hXmfaI2Jv8gob7RZ4Dsy1wxr0sX7T3SbI1oSGEABaehHOBh6majG8Ja89xjIF0EeSip+DCRDYlgXe0OmlMlFGlUofKHL8AOe6d+0GF4ZUcnR940p3p306WullNaE='

token:
  expiration_time: 864000000 # 60 * 60 * 24 * 1000
  secret: '{cipher}AQBXQsgxJKJo8ZHry7s3pvRqZ1g1ajGYtlfm2LW0ubskEsIF3wKkmPlbtyO71x6pA8uDbuwEQBNX6ywARsJL9ISietkZuKMpVaKWzVDGOjIdDhC3SVIWOz18HywpEoIgIX3vQZ5SLmKXRqDRnblds3QIt3a3ZRHQuD293gFOfzPJAoexF5BiJcsjgtzrEO4AQ2ZzGjSpPcSAjv4TgBLf41l5wCmZhSaX/ICbF+AosV+Ok4kwsfYxkmSMTN3w8Fg8bIabWoJSEN3WXC7ikwHMgRJadjy/m0KVXuxmnrwj4q99UPwYlcsLNT4G7ih3WXUWwcBbDU29ARC1DXYFohxaUdDjaHbOTO31lyCEy/Tc/K95PNLH7/r4mSzviS0czigSxcEaz1Xl3PDhfX71gQNi28VK'

gateway:
  ip: 192.168.0.2

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item
